import express from "express";
const router = express.Router();

// Import routes
import authRoutes from "../routes/AuthRoute.js";
import blogPostRoutes from "../routes/BlogPostRoute.js";
import schoolRoutes from "../routes/academic/SchoolRoute.js";
import sessionRoutes from "../routes/academic/SessionRoute.js";
import shiftRoutes from "../routes/academic/ShiftRoute.js";
import mediumRoutes from "../routes/academic/MediumRoute.js";
import classRoutes from "../routes/academic/ClassRoute.js";
import groupRoutes from "../routes/academic/GroupRoute.js";
import teacherRoutes from "../routes/teacher/TeacherRoute.js";
import sectionRoutes from "../routes/academic/SectionRoute.js";
import subjectRoutes from "../routes/academic/SubjectRoute.js";
import classWiseSubjectRoutes from "../routes/academic/ClassWiseSubjectRoute.js";
import studentRoutes from "../routes/student/studentRoute.js";
import staffRoutes from "../routes/staff/StaffRoute.js";
import studentAttendanceRoutes from "../routes/attendance/StudentAttendanceRoute.js";
import teacherAttendanceRoutes from "../routes/attendance/TeacherAttendanceRoute.js";
import examTypeRoutes from "../routes/examination/ExamTypeRoute.js";
import examRoutes from "../routes/examination/ExamRoute.js";
import examMarksRoutes from "../routes/examination/ExamMarksRoute.js";
import examResultRoutes from "../routes/examination/ExamResultRoute.js";
import gradingSystemRoutes from "../routes/examination/GradingSystemRoute.js";
import feeTypeRoutes from "../routes/fees/FeeTypeRoute.js";
import feeStructureRoutes from "../routes/fees/FeeStructureRoute.js";
import feeCollectionRoutes from "../routes/fees/FeeCollectionRoute.js";
import accountsRoutes from "../routes/fees/AccountsRoute.js";
import bookRoutes from "../routes/library/BookRoute.js";
import bookIssueRoutes from "../routes/library/BookIssueRoute.js";
import noticeRoutes from "../routes/communication/NoticeRoute.js";
import homeworkRoutes from "../routes/homework/HomeworkRoute.js";
import homeworkSubmissionRoutes from "../routes/homework/HomeworkSubmissionRoute.js";
import eventRoutes from "../routes/event/EventRoute.js";
import salaryRoutes from "../routes/salary/SalaryRoute.js";
import staffAttendanceRoutes from "../routes/attendance/StaffAttendanceRoute.js";
import transportRouteRoutes from "../routes/transport/TransportRouteRoute.js";
import vehicleRoutes from "../routes/transport/VehicleRoute.js";
import hostelRoutes from "../routes/hostel/HostelRoute.js";
import hostelRoomRoutes from "../routes/hostel/HostelRoomRoute.js";
import studentPromotionRoutes from "../routes/student/StudentPromotionRoute.js";
import dashboardRoutes from "../routes/dashboard/DashboardRoute.js";
import idCardRoutes from "../routes/utils/IDCardRoute.js";
import reportCardRoutes from "../routes/utils/ReportCardRoute.js";
import timeTableRoutes from "../routes/timetable/TimeTableRoute.js";
import leaveRoutes from "../routes/leave/LeaveRoute.js";
import syllabusRoutes from "../routes/syllabus/SyllabusRoute.js";
import certificateRoutes from "../routes/certificate/CertificateRoute.js";
import adminUserRoutes from "../routes/user/AdminUserRoute.js";
import roleRoutes from "../routes/user/RoleRoute.js";
import settingsRoutes from "../routes/settings/SettingsRoute.js";
import onlineClassRoutes from "../routes/online/OnlineClassRoute.js";
import smsRoutes from "../routes/communication/SMSRoute.js";
import emailRoutes from "../routes/communication/EmailRoute.js";

// Use routes
router.use("/auth", authRoutes);
router.use("/blogposts", blogPostRoutes);
router.use("/schools", schoolRoutes);
router.use("/sessions", sessionRoutes);
router.use("/shifts", shiftRoutes);
router.use("/mediums", mediumRoutes);
router.use("/classes", classRoutes);
router.use("/groups", groupRoutes);
router.use("/teachers", teacherRoutes);
router.use("/sections", sectionRoutes);
router.use("/subjects", subjectRoutes);
router.use("/class-wise-subjects", classWiseSubjectRoutes);
router.use("/students", studentRoutes);
router.use("/staff", staffRoutes);
router.use("/attendance/students", studentAttendanceRoutes);
router.use("/attendance/teachers", teacherAttendanceRoutes);
router.use("/exam-types", examTypeRoutes);
router.use("/exams", examRoutes);
router.use("/exam-marks", examMarksRoutes);
router.use("/exam-results", examResultRoutes);
router.use("/grading-systems", gradingSystemRoutes);
router.use("/fee-types", feeTypeRoutes);
router.use("/fee-structures", feeStructureRoutes);
router.use("/fee-collections", feeCollectionRoutes);
router.use("/accounts", accountsRoutes);
router.use("/books", bookRoutes);
router.use("/book-issues", bookIssueRoutes);
router.use("/notices", noticeRoutes);
router.use("/homework", homeworkRoutes);
router.use("/homework-submissions", homeworkSubmissionRoutes);
router.use("/events", eventRoutes);
router.use("/salaries", salaryRoutes);
router.use("/attendance/staff", staffAttendanceRoutes);
router.use("/transport-routes", transportRouteRoutes);
router.use("/vehicles", vehicleRoutes);
router.use("/hostels", hostelRoutes);
router.use("/hostel-rooms", hostelRoomRoutes);
router.use("/student-promotions", studentPromotionRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/id-cards", idCardRoutes);
router.use("/report-cards", reportCardRoutes);
router.use("/timetables", timeTableRoutes);
router.use("/leaves", leaveRoutes);
router.use("/syllabus", syllabusRoutes);
router.use("/certificates", certificateRoutes);
router.use("/admin-users", adminUserRoutes);
router.use("/roles", roleRoutes);
router.use("/settings", settingsRoutes);
router.use("/online-classes", onlineClassRoutes);
router.use("/sms", smsRoutes);
router.use("/emails", emailRoutes);

export default router;
